### ISSUE TITLE
Doesn't work with 1.4.1

### ISSUE THREAD

**Issue by FrmrJon** [ddewar/FS22_UniversalAutoloadModSettingsAddon#1]
Hi, I have downloaded this mod, and it isn't working for Fs 22 Version 1.4.1. The game loads to 60% and stops.

**Comment by ddewar** [comment]
Thanks for letting me know. I had this one on hold until I got the Modhub version working. I will try to release a working version of this ASAP.

**Comment by ddewar** [comment]
Try this version:

https://github.com/ddewar/FS22_UniversalAutoloadModSettingsAddon/releases/tag/v0.0.1-beta

**Comment by FrmrJon** [comment]
That seems to have worked. Could you post some info on how to use the mod? I have it installed, but I don't know how to use it.

**Comment by ddewar** [comment]
Yeah, sorry this mod has mostly been on hold while I get the modhub one all ready. I will get something better in the readme soon.

Until then, basics are add this mod and UniversalAutoload, start the save game once. It will create a file called "UniversalAutoload.xml" is your modSettings folder. In that file there will be a few examples, and you can use those to help craft any custom Autoload loading areas. For instructions on how to build the configs check out https://github.com/loki79uk/FS22_UniversalAutoload readme file. After that any custom configs should be applied and will add autoload to those trailers.
