### ISSUE TITLE
A question only - do you plan to publish the package?

### ISSUE THREAD

**Issue by DrewCZ** [ddewar/FS22_UniversalAutoloadModSettingsAddon#2]
A question only - do you plan to publish the package? It will be easier to download.
Thank you.

**Comment by ddewar** [comment]
You should be able to download it via the tags section pretty easily? I will look into it though. Github seems to be not doing what I expect.

**Comment by ddewar** [comment]
Ignore everything above. I haven't released anything on this one yet. 😆  I will get a version of it out. Warning this project has been kinda idol because it does not support multiplayer right now.

**Comment by ddewar** [comment]
Does this version not work at all?

https://github.com/ddewar/FS22_UniversalAutoloadModSettingsAddon/releases/tag/v0.0.1-beta

I am way behind on this project.

**Comment by DrewCZ** [comment]
Will check and let you know. Thank you.
BTW I'm able to download it, but this way using tags isn't pretty clear for other people. And I'm fighting about your mods rather than Autoload ;)

**Comment by ddewar** [comment]
The plan was to use tags until I make an official release, as these are all pre-releases. If this is confusing though, I can for sure reconsider.

**Comment by DrewCZ** [comment]
Mod works well in SP and as server in MP also. Log clear. 

![obrazek](https://user-images.githubusercontent.com/26751314/173422646-91e33c37-6bca-466b-91cf-253c0d99f14b.png)

**Comment by DrewCZ** [comment]
> The plan was to use tags until I make an official release, as these are all pre-releases. If this is confusing though, I can for sure reconsider.

Okay, full respect. You have plan and that was only question. ;-) Thank you!

**Comment by DrewCZ** [comment]
> Mod works well in SP and as server in MP also. Log clear.
> 
> 

btw - this is annaburger superstructure attached on the tandem dolly, this means two attached "vehicles" on tractor back.
